let flightState = [
	{
		id: 1,
		AirportCode: "LAX",
		AirportName: "Los Angeles",
		from: "LAX",
		to: "Austin",
		Departure: "25 Jun 2019",
		Arrival: "25 Jun 2019",
		time: "1:05 AM",
		AncillaryServices: [
			{ id: 1, Service: "Frequent flyer information" },
			{ id: 2, Service: "Region" },
			{ id: 3, Service: "Route" },
			{ id: 4, Service: "Cabin" },
			{ id: 5, Service: "Fare basis code" },
		],
		SpecialMeals: [
			{ id: 1, Service: "ALLERGEN MEAL" },
			{ id: 2, Service: "ASIAN VEGETARIAN MEAL" },
			{ id: 3, Service: "BABY MEAL" },
			{ id: 4, Service: "BLAND MEAL" },
			{ id: 5, Service: "DIABETIC MEAL" },
			{ id: 6, Service: "FRUIT PLATTER MEAL" },
			{ id: 7, Service: "GLUTEN FREE MEAL" },
			{ id: 8, Service: "HINDU NON VEG MEAL" },
			{ id: 9, Service: "KOSHER MEALS" },
			{ id: 10, Service: "LOW CALORIE MEALS" },
			{ id: 11, Service: "LOW FAT MEALS" },
			{ id: 12, Service: "LOW SALT MEALS" },
			{ id: 13, Service: "MUSLIM MEALS" },
			{ id: 14, Service: "RAW VEGETARIAN" },
			{ id: 15, Service: "SEAFOOD MEAL" },
			{ id: 16, Service: "VEGAN/VEGETARIAN MEAL" },
			{ id: 17, Service: "VEGETARIAN JAIN MEAL" },
			{ id: 18, Service: "VEGETARIAN LACTO OVO" },
			{ id: 19, Service: "VOML – VEGETARIAN ORIENTAL MEAL" },
		],
		ShoppingItems: [
			{ id: 1, Service: "Network Carriers" },
			{ id: 2, Service: "Direct Payment Carriers" },
		],
	},
	{
		id: 2,
		AirportCode: "Aus",
		AirportName: "Austin",
		from: "Aus",
		to: "LAX",
		Departure: "25 Jun 2019",
		Arrival: "25 Jun 2019",
		time: "3:05 AM",
		AncillaryServices: [],
		SpecialMeals: [],
		ShoppingItems: [],
	},
	{
		id: 3,
		AirportCode: "CAL",
		AirportName: "California",
		from: "CAL",
		to: "NY",
		Departure: "15 Jun 2019",
		Arrival: "15 Jun 2019",
		time: "10:05 AM",
		AncillaryServices: [],
		SpecialMeals: [],
		ShoppingItems: [],
	},
];

export default flightState;
