let seatRows = [
	{
		flightId: 0,

		rows: [
			{
				rowId: 0,
				id: 0,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{
				rowId: 1,
				id: 1,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{ rowId: 2, id: 2, seats: [] },
			{
				rowId: 3,
				id: 3,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
		],
	},
	{
		flightId: 1,

		rows: [
			{
				rowId: 0,
				id: 10,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{
				rowId: 1,
				id: 11,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{ rowId: 2, id: 12, seats: [] },
			{
				rowId: 3,
				id: 13,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
		],
	},
	{
		flightId: 2,

		rows: [
			{
				rowId: 0,
				id: 20,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{
				rowId: 1,
				id: 21,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
			{ rowId: 2, id: 22, seats: [] },
			{
				rowId: 3,
				id: 23,
				seats: [
					{ id: 1, number: "A" },
					{ id: 2, number: "B" },
					{ id: 3, number: "C" },
					{ id: 4, number: "D" },
					{ id: 5, number: "E" },
					{ id: 6, number: "F" },
					{ id: 7, number: "G" },
					{ id: 8, number: "H" },
					{ id: 9, number: "I" },
					{ id: 10, number: "J" },
				],
			},
		],
	},
];
export default seatRows;
