let seatRows = [
		[
			{ id: 1, number: 'A' },
			{ id: 2, number: 'B' },
			{ id: 3, number: 'C' },
			{ id: 4, number: 'D' },
			{ id: 5, number: 'E' },
			{ id: 6, number: 'F' },
			{ id: 7, number: 'G' },
			{ id: 8, number: 'H' },
			{ id: 9, number: 'I' },
			{ id: 10, number: 'J' },
		],
		[
			{ id: 1, number: 'A' },
			{ id: 2, number: 'B' },
			{ id: 3, number: 'C' },
			{ id: 4, number: 'D' },
			{ id: 5, number: 'E' },
			{ id: 6, number: 'F' },
			{ id: 7, number: 'G' },
			{ id: 8, number: 'H' },
			{ id: 9, number: 'I' },
			{ id: 10, number: 'J' },
		],
		[],
		[
			{ id: 1, number: 'A' },
			{ id: 2, number: 'B' },
			{ id: 3, number: 'C' },
			{ id: 4, number: 'D' },
			{ id: 5, number: 'E' },
			{ id: 6, number: 'F' },
			{ id: 7, number: 'G' },
			{ id: 8, number: 'H' },
			{ id: 9, number: 'I' },
			{ id: 10, number: 'J' },
		],
];
	export default seatRows;
